# Generated by Django 2.2.1 on 2019-05-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='availability',
            field=models.CharField(choices=[('AL', 'Available for Order'), ('NA', 'Not Available'), ('AN', 'Available Now')], default='AN', max_length=2),
        ),
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(upload_to='./media'),
        ),
        migrations.AlterField(
            model_name='art',
            name='timeframe_for_order',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
