# Generated by Django 2.2.1 on 2019-05-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20190503_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='availability',
            field=models.CharField(choices=[('AL', 'Available for Order'), ('AN', 'Available Now'), ('NA', 'Not Available')], default='AN', max_length=2),
        ),
    ]
