# Generated by Django 2.2.1 on 2019-05-03 11:54

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_auto_20190503_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.TextField(blank=True, max_length=50)),
                ('biography', models.TextField(blank=True)),
                ('profile_picture_path', models.ImageField(upload_to='./media/artist')),
                ('twitter', models.URLField(blank=True, max_length=50)),
                ('instagram', models.URLField(blank=True, max_length=50)),
                ('facebook', models.URLField(blank=True, max_length=50)),
                ('gender', models.BooleanField()),
                ('rating', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='art',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='art',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='availability',
            field=models.CharField(choices=[('AL', 'Available for Order'), ('NA', 'Not Available'), ('AN', 'Available Now')], default='AN', max_length=2),
        ),
        migrations.AlterField(
            model_name='art',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.ImageField(blank=True, upload_to='./media/art'),
        ),
        migrations.AddField(
            model_name='art',
            name='artist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='art.Artist'),
        ),
    ]
